# Name: Harsh Vora
Student Id: A20445400
Course: Cs-512
Semester: Fall 2020


In [1]:
import numpy as np
import numpy.linalg as la

m = np.matrix('1, 2, 3')
n = np.matrix('4, 5, 6')
o = np.matrix('-1, 1, 3')

print("Question 1")
print("1. 2A - B")
print()
print((2*np.matrix(m)) - n)
print("-"*50)

print("Question 2")
print("1. ||A||")
print()
print(la.norm(m))
print("2. angle of A relative to the positive X axis")
print()
print(np.degrees(np.arccos(m.item(0)/la.norm(m))))
print("-"*50)

print("Question 3")
print("a unit vector in the direction of A")
print()
print(m/la.norm(m))
print("-"*50)

print("Question 4")
print("the direction cosines of A")
print()
print(np.degrees(np.arccos(m / la.norm(m))))
print("-"*50)

A = np.array([1,2,3])
B = np.array([4,5,6])
C = np.array([-1,1,3])
result1 = 0
result2 = 0
print("Question 5")
print("1. A . B")
print()
for i in range (len(A)):
    result1 += A[i]*B[i]
print(result1)
print("2. B . A")
print()
for i in range (len(A)):
    result2 += B[i]*A[i]
print(result2)
print("-"*50)

result3=0
print("Question 6")
print("the angle between A and B")
print()
for i in range (len(A)):
    result3 += A[i]*B[i]
magA = la.norm(A)
magB =la.norm(B)
mag = magA * magB
angle =np.arccos(result3/mag)
print(np.degrees(angle))
print("-"*50)

dot_pro = 0
print("Question 7")
print("a vector which is perpendicular to A")
print()
per_1 = np.array([-3, 0, 1])
for i in range (len(A)):
    dot_pro += A[i] * per_1[i]
print("A .[-3, 0 1] = ",dot_pro)
print("thus vector A and",per_1,"are perpendicular to each other")
print("-"*50)

print("Question 8")
print("1. A × B")
print()
print(np.cross(m,n))
print("2. B × A")
print()
print(np.cross(n,m))
print("-"*50)

dot_pro1 = 0
dot_pro2 = 0
print("Question 9")
print("a vector which is perpendicular to both A and B")
print()
per_2 = np.array([1, -2, 1])
for i in range (len(A)):
    dot_pro1 += A[i] * per_2[i]
print("A *[1, -2, 1]= ",dot_pro1)
for i in range (len(B)):
    dot_pro2 += B[i] * per_2[i]
print("B *[1, -2, 1]= ",dot_pro2)
print("thus vector ",per_2,"is perpendicular to both vector A and B")
print("-"*50)

print("Question 10")
print("the linear dependency between A, B, C")
print("Ans: Matrix A, B, C are linearly dependent")

print("-"*50)

print("Question 11")
print("1. transpose of A * B")
print()
print(np.dot(np.transpose(m),n))
print("2. A * Transpose of B")
print()
print(np.dot(m,np.transpose(n)))

Question 1
1. 2A - B

[[-2 -1  0]]
--------------------------------------------------
Question 2
1. ||A||

3.7416573867739413
2. angle of A relative to the positive X axis

74.498640433063
--------------------------------------------------
Question 3
a unit vector in the direction of A

[[0.26726124 0.53452248 0.80178373]]
--------------------------------------------------
Question 4
the direction cosines of A

[[74.49864043 57.68846676 36.6992252 ]]
--------------------------------------------------
Question 5
1. A . B

32
2. B . A

32
--------------------------------------------------
Question 6
the angle between A and B

12.933154491899135
--------------------------------------------------
Question 7
a vector which is perpendicular to A

A .[-3, 0 1] =  0
thus vector A and [-3  0  1] are perpendicular to each other
--------------------------------------------------
Question 8
1. A × B

[[-3  6 -3]]
2. B × A

[[ 3 -6  3]]
--------------------------------------------------
Question 9


In [3]:
import numpy as np
import numpy.linalg as la
p = np.matrix('1 2 3; 4 -2 3; 0 5 -1')
q = np.matrix('1  2 1 ; 2 1 -4; 3 -2 1')
r = np.matrix('1 2 3; 4 5 6; -1 1 3')

print("Question 1")
print("1. 2A - B")
print()
print((2 * p) - q)
print("-"*50)

print("Question 2")
print("1. A * B")
print()
print(p * q)
print("2. B * A")
print()
print(q * p)
print("-"*50)

print("Question 3")
print("1. Transpose of (A * B)")
print()
print(np.transpose(p * q))
print("2. Transpose of B * Transpose of A")
print()
print(np.transpose(q) * np.transpose(p))
print("-"*50)

print("Question 4")
print("1. |A| ")
print()
print(la.det(p))
print("2. |C| ")
print()
print(la.det(r))
print("-"*50)

print("Question 5")
print("5. the matrix (A, B, or C) in which the row vectors form an orthogonal set")
print()
m1 = np.array([1, 2, 1])
m2 = np.array([2, 1, -4])
m3 = np.array([3, -2, 1])
result4 = 0
result5 = 0
result6 = 0
for i in range(len(m1)):
    result4 += m1[i] * m2[i];
print("R1 * R2= ",result4)
for i in range(len(m1)):
    result4 += m2[i] * m3[i];
print("R2 * R3= ",result5)
for i in range(len(m1)):
    result4 += m3[i] * m1[i];
print("R3 * R2= ",result6)
print("Thus matrix B is the one in which row vectors form an orthogonal set ")
print("-"*50)

print("Question 6")
print("1. Inverse of A")
print()
print(la.inv(p))
print("2. Inverse of B")
print()
print(la.inv(q))



Question 1
1. 2A - B

[[ 1  2  5]
 [ 6 -5 10]
 [-3 12 -3]]
--------------------------------------------------
Question 2
1. A * B

[[ 14  -2  -4]
 [  9   0  15]
 [  7   7 -21]]
2. B * A

[[  9   3   8]
 [  6 -18  13]
 [ -5  15   2]]
--------------------------------------------------
Question 3
1. Transpose of (A * B)

[[ 14   9   7]
 [ -2   0   7]
 [ -4  15 -21]]
2. Transpose of B * Transpose of A

[[ 14   9   7]
 [ -2   0   7]
 [ -4  15 -21]]
--------------------------------------------------
Question 4
1. |A| 

54.999999999999964
2. |C| 

7.494005416219837e-16
--------------------------------------------------
Question 5
5. the matrix (A, B, or C) in which the row vectors form an orthogonal set

R1 * R2=  0
R2 * R3=  0
R3 * R2=  0
Thus matrix B is the one in which row vectors form an orthogonal set 
--------------------------------------------------
Question 6
1. Inverse of A

[[-0.23636364  0.30909091  0.21818182]
 [ 0.07272727 -0.01818182  0.16363636]
 [ 0.36363636 -0.09090909 -0.1

In [2]:
import numpy as np
import numpy.linalg as la
a = np.matrix('1 2; 3 2')
b = np.matrix('2 -2; -2 5')

w, v = la.eig(a)

print("Question 1")
print("1. Eigen Values")
print()
print(np.round(w))
print("2. Eigen Vectors")
print()
print(np.round(v))
print("-"*50)

print("Question 2")
print()
print(np.round(la.inv(v) * a * v) )
print("-"*50)

print("Question 3")
print()
va1 = v[:,0]
va2 = v[:,1]

print(np.vdot(va1,va2))
print("-"*50)

print("Question 4")
print()
w1, v1 = la.eig(b)
v1b1 = v1[:,0]
v1b2 = v1[:,1]
print(np.round(np.vdot(v1b1,v1b2)))
print("-"*50)

print("Question 5")
print()
print("Both the vector are perpendicular to each other. i.e. They form an orthogonal pair")

Question 1
1. Eigen Values

[-1.  4.]
2. Eigen Vectors

[[-1. -1.]
 [ 1. -1.]]
--------------------------------------------------
Question 2

[[-1. -0.]
 [ 0.  4.]]
--------------------------------------------------
Question 3

[[0.39223227]]
--------------------------------------------------
Question 4

[[-0.]]
--------------------------------------------------
Question 5

Both the vector are perpendicular to each other. i.e. They form an orthogonal pair
